In [11]:
#Question 1) Arrays

import numpy

def arrays(arr):
    arr_1=numpy.array(arr,float)
    return arr_1[-1::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [28]:
#Question 2) Shape and Reshape

import numpy
arr=input().split()
arr_1=numpy.array(arr,int)
arr_2=numpy.reshape(arr_1,(3,3))
print(arr_2)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#Question 3) Transpose and Flatten

import numpy
n,m=map(int,input().split())
arr=numpy.array([input().strip().split() for _ in range(n)],int)
print(numpy.transpose(arr))
print(arr.flatten())

2 3
4 5 6
2 3 4
[[4 2]
 [5 3]
 [6 4]]
[4 5 6 2 3 4]


In [17]:
#Question 4) Concatenate

import numpy
n,m,p=map(int,input().split())
arr_1=numpy.array([input().strip().split() for _ in range(n)],int)
arr_2=numpy.array([input().strip().split() for _ in range(m)],int)
concatenate=numpy.concatenate((arr_1,arr_2),axis=0)
print(concatenate)

4 3 2
1 4
1 4
1 4
1 4
3 4
3 4
3 4
[[1 4]
 [1 4]
 [1 4]
 [1 4]
 [3 4]
 [3 4]
 [3 4]]


In [7]:
#Question 5) Zeros and Onnes

import numpy
dimensions=tuple(map(int,input().strip().split()))
x=numpy.zeros(dimensions,int)
z=numpy.ones(dimensions,int)
print(x)
print(z)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [9]:
#Question 6) Eye and Identity

import numpy
numpy.set_printoptions(legacy='1.13')
n,m=map(int,input().strip().split())
print(numpy.eye(n,m,0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [15]:
#Question 7) Array Mathematics

import numpy
n,m=map(int,input().strip().split())
a=numpy.array([input().strip().split() for i in range(n)],int)
b=numpy.array([input().strip().split() for j in range(n)],int)
print(numpy.add(a,b))
print(numpy.subtract(a,b))
print(numpy.multiply(a,b))
print(numpy.floor_divide(a,b))
print(numpy.mod(a,b))
print(numpy.power(a,b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [27]:
#Question 8) Floor,Ceil and Rint

import numpy
numpy.set_printoptions(legacy="1.13")
elements=input().strip().split(" ")
array=numpy.array(elements,float)
print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [32]:
#Question 9) Sum and Prod

import numpy
n,m=map(int,input().strip().split())
a=numpy.array([input().strip().split() for i in range(n)],int)
sum_of_a=numpy.sum(a,axis=0)
product=numpy.prod(sum_of_a)
print(product)

2 2
1 2
3 4
24


In [36]:
#Question 10) Min and Max

import numpy
n,m=map(int,input().strip().split())
array=numpy.array([input().strip().split() for i in range(n)],int)
minimum=numpy.min(array,axis=1)
maximum=numpy.max(minimum)
print(maximum)

4 2
2 5
3 7
1 3
4 0
3


In [38]:
#Question 11) Mean,Var and Std

import numpy
n,m=map(int,input().strip().split())
array=numpy.array([input().strip().split() for i in range(n)],int)
compute_mean=numpy.mean(array,axis=1)
compute_var=numpy.var(array,axis=0)
compute_std=round(numpy.std(array),11)
print(compute_mean)
print(compute_var)
print(compute_std)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [41]:
#Question 12) Dot and Cross

import numpy
n=int(input())
a=numpy.array([input().strip().split() for i in range(n)],int)
b=numpy.array([input().strip().split() for i in range(n)],int)
print(numpy.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [45]:
#Question 13) Inner and Outer

import numpy
a=input().strip().split()
b=input().strip().split()
array_a=numpy.array(a,int)
array_b=numpy.array(b,int)
print(numpy.inner(array_a,array_b))
print(numpy.outer(array_a,array_b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [58]:
#Question 14) Polynomials

import numpy
p=input().strip().split()
p_array=numpy.array(p,float)
x=float(input())
print(numpy.polyval(p_array,x))

1.1 2 3
0
3.0


In [56]:
# Question 15) Linear Algebra

import numpy
n=int(input())
arr=numpy.array([input().strip().split() for i in range(n)],float)
determinant=round(numpy.linalg.det(arr),2)
print(determinant)

2
1.1 1.1
1.1 1.1
0.0
